=== legendarry24/Internet-Technologies/LAB2/input.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://sherbakov.nure.ua/practice7/entity"
	xmlns:tns="http://sherbakov.nure.ua/practice7/entity">

	<element name="Flowers">

		<complexType>
			<sequence>
				<element name="Flower" type="tns:Flower" minOccurs="2"
					maxOccurs="unbounded" />
			</sequence>
		</complexType>
	</element>

	<complexType name="Flower">
		<sequence>
			<element name="Name" type="token" />

			<element name="Origin" type="token" />
			<element name="VisualParameters" type="tns:VisualParameters" />
			<element name="GrovingTips" type="tns:GrovingTips" />
			<element name="Multipling" type="tns:Multipling" />
			<element name="Price">
				<simpleType>
					<restriction base="decimal">
						<fractionDigits value="2"></fractionDigits>
						<totalDigits value="4"></totalDigits>
						<minExclusive value="0"></minExclusive>
					</restriction>
				</simpleType>
			</element>
		</sequence>
		<attribute name="Soil" type="tns:Soil" use="optional" />
		<attribute name="Id" use="required">
			<simpleType>
				<restriction base="int">
					<minExclusive value="0"></minExclusive>
				</restriction>
			</simpleType>
		</attribute>
	</complexType>

	<simpleType name="Multipling">
		<restriction base="token">
			<enumeration value="leaves"></enumeration>
			<enumeration value="feces"></enumeration>
			<enumeration value="seeds"></enumeration>
			<pattern value="leaves|feces|seeds" />
		</restriction>
	</simpleType>

	<simpleType name="Soil">
		<restriction base="token">
			<pattern value="podzolic|unpaved|wood-podzolic" />
		</restriction>
	</simpleType>

	<complexType name="VisualParameters">
		<choice>
			<element name="StalkColor" type="token" />
			<element name="ColorOfLeaves">
				<simpleType>
					<restriction base="token">
						<minLength value="3"></minLength>
						<maxLength value="10"></maxLength>
					</restriction>
				</simpleType>
			</element>
			<element name="AveragePlantSize">
				<simpleType>
					<restriction base="int">
						<minExclusive value="0" />
					</restriction>
				</simpleType>
			</element>
		</choice>
	</complexType>

	<complexType name="GrovingTips">
		<all>
			<element name="Temperature" minOccurs="0">
				<simpleType>
					<restriction base="int">
						<minInclusive value="0" />
						<maxInclusive value="60" />
					</restriction>
				</simpleType>
			</element>

			<element name="Lighting" type="boolean" minOccurs="0"></element>

			<element name="Watering" minOccurs="0">
				<simpleType>
					<restriction base="int">
						<minInclusive value="0" />
					</restriction>
				</simpleType>
			</element>
		</all>
	</complexType>
</schema>

=== legendarry24/Internet-Technologies/LAB2/output.sax.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<tns:Flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://sherbakov.nure.ua/practice7/entity input.xsd" xmlns:tns="http://sherbakov.nure.ua/practice7/entity">
    <Flower>
        <Name>Thoren</Name>
        <Soil>unpaved</Soil>
        <Origin>Asia</Origin>
        <VisualParameters>
            <StalkColor>Green</StalkColor>
            <ColorOfLeaves>Violet</ColorOfLeaves>
            <AveragePlantSize>30</AveragePlantSize>
        </VisualParameters>
        <GrovingTips>
            <Temperature>22</Temperature>
            <Lighting>true</Lighting>
            <Watering>60</Watering>
        </GrovingTips>
        <Multipling>seeds</Multipling>
    </Flower>
    <Flower>
        <Name>Hedychium</Name>
        <Soil>wood-podzolic</Soil>
        <Origin>South Asia</Origin>
        <VisualParameters>
            <StalkColor>Green</StalkColor>
            <ColorOfLeaves>Yellow</ColorOfLeaves>
            <AveragePlantSize>45</AveragePlantSize>
        </VisualParameters>
        <GrovingTips>
            <Temperature>27</Temperature>
            <Lighting>false</Lighting>
            <Watering>105</Watering>
        </GrovingTips>
        <Multipling>feces</Multipling>
    </Flower>
    <Flower>
        <Name>Rose</Name>
        <Soil>podzolic</Soil>
        <Origin>Holland</Origin>
        <VisualParameters>
            <StalkColor>Green</StalkColor>
            <ColorOfLeaves>Red</ColorOfLeaves>
            <AveragePlantSize>60</AveragePlantSize>
        </VisualParameters>
        <GrovingTips>
            <Temperature>20</Temperature>
            <Lighting>true</Lighting>
            <Watering>80</Watering>
        </GrovingTips>
        <Multipling>leaves</Multipling>
    </Flower>
</tns:Flowers>

=== legendarry24/Internet-Technologies/LAB34WebServer/output.stax.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<tns:Flowers
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://sherbakov.nure.ua/practice7/entity input.xsd"
	xmlns:tns="http://sherbakov.nure.ua/practice7/entity">
	<Flower Soil="podzolic" id="1">
		<Name>Rose</Name>
		<Origin>Holland</Origin>
		<VisualParameters>
			<StalkColor>Grey</StalkColor>
			<ColorOfLeaves>Red</ColorOfLeaves>
			<AveragePlantSize>60</AveragePlantSize>
		</VisualParameters>
		<GrovingTips>
			<Temperature>20</Temperature>
			<Lighting>true</Lighting>
			<Watering>80</Watering>
		</GrovingTips>
		<Multipling>feces</Multipling>
		<Price>15.59</Price>
	</Flower>
	<Flower Soil="unpaved" id="3">
		<Name>Thoren</Name>
		<Origin>Asia</Origin>
		<VisualParameters>
			<StalkColor>Green</StalkColor>
			<ColorOfLeaves>Violet</ColorOfLeaves>
			<AveragePlantSize>55</AveragePlantSize>
		</VisualParameters>
		<GrovingTips>
			<Temperature>22</Temperature>
			<Lighting>true</Lighting>
			<Watering>60</Watering>
		</GrovingTips>
		<Multipling>seeds</Multipling>
		<Price>16.49</Price>
	</Flower>
	<Flower Soil="unpaved" id="4">
		<Name>Kermek</Name>
		<Origin>Asia</Origin>
		<VisualParameters>
			<StalkColor>Green</StalkColor>
			<ColorOfLeaves>Blue</ColorOfLeaves>
			<AveragePlantSize>34</AveragePlantSize>
		</VisualParameters>
		<GrovingTips>
			<Temperature>22</Temperature>
			<Lighting>true</Lighting>
			<Watering>60</Watering>
		</GrovingTips>
		<Multipling>seeds</Multipling>
		<Price>20.99</Price>
	</Flower>
	<Flower Soil="unpaved" id="5">
		<Name>Abelia</Name>
		<Origin>Japan</Origin>
		<VisualParameters>
			<StalkColor>Green</StalkColor>
			<ColorOfLeaves>Violet</ColorOfLeaves>
			<AveragePlantSize>55</AveragePlantSize>
		</VisualParameters>
		<GrovingTips>
			<Temperature>22</Temperature>
			<Lighting>true</Lighting>
			<Watering>60</Watering>
		</GrovingTips>
		<Multipling>seeds</Multipling>
		<Price>20.99</Price>
	</Flower>
	<Flower Soil="wood-podzolic" id="2">
		<Name>Hedychium</Name>
		<Origin>South Asia</Origin>
		<VisualParameters>
			<StalkColor>Green</StalkColor>
			<ColorOfLeaves>Blue</ColorOfLeaves>
			<AveragePlantSize>12</AveragePlantSize>
		</VisualParameters>
		<GrovingTips>
			<Temperature>27</Temperature>
			<Lighting>false</Lighting>
			<Watering>105</Watering>
		</GrovingTips>
		<Multipling>feces</Multipling>
		<Price>12.79</Price>
	</Flower>
</tns:Flowers>

=== legendarry24/Internet-Technologies/LAB2/input1.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Flowers
	xmlns:tns="http://sherbakov.nure.ua/practice7/entity"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://sherbakov.nure.ua/practice7/entity input.xsd ">
	<Flower Id="1" Soil="podzolic">
		<Name>Rose</Name>
		<Origin>Holland</Origin>
		<VisualParameters>
			<AveragePlantSize>60</AveragePlantSize>
		</VisualParameters>
		<GrovingTips>
			<Temperature>20</Temperature>
			<Watering>80</Watering>
			<Lighting>true</Lighting>
		</GrovingTips>
		<Multipling>feces</Multipling>
		<Price>15.59</Price>
	</Flower>
	<Flower Id="2" Soil="wood-podzolic">
		<Name>Hedychium</Name>
		<Origin>South Asia</Origin>
		<VisualParameters>
			<StalkColor>Green</StalkColor>
		</VisualParameters>
		<GrovingTips>
			<Temperature>27</Temperature>
			<Watering>105</Watering>
			<Lighting>false</Lighting>
		</GrovingTips>
		<Multipling>feces</Multipling>
		<Price>12.79</Price>
	</Flower>

	<Flower Id="3">
		<Name>Thoren</Name>
		<Origin>Asia</Origin>
		<VisualParameters>
			<ColorOfLeaves>Violet</ColorOfLeaves>
		</VisualParameters>
		<GrovingTips>
			<Watering>60</Watering>
			<Temperature>22</Temperature>
			<Lighting>true</Lighting>
		</GrovingTips>
		<Multipling>seeds</Multipling>
		<Price>16.49</Price>
	</Flower>

	<Flower Id="4" Soil="unpaved">
		<Name>Kermek</Name>
		<Origin>Asia</Origin>
		<VisualParameters>
			<ColorOfLeaves>Blue</ColorOfLeaves>
		</VisualParameters>
		<GrovingTips>
			<Watering>60</Watering>
			<Temperature>22</Temperature>
			<Lighting>true</Lighting>
		</GrovingTips>
		<Multipling>seeds</Multipling>
		<Price>20.99</Price>
	</Flower>

	<Flower Id="5" Soil="unpaved">
		<Name>Abelia</Name>
		<Origin>Japan</Origin>
		<VisualParameters>
			<ColorOfLeaves>Blue</ColorOfLeaves>
		</VisualParameters>
		<GrovingTips>
			<Watering>60</Watering>
			<Temperature>22</Temperature>
			<Lighting>true</Lighting>
		</GrovingTips>
		<Multipling>seeds</Multipling>
		<Price>20.99</Price>
	</Flower>
</tns:Flowers>

=== legendarry24/Internet-Technologies/LAB3/output.dom.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<tns:Flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://sherbakov.nure.ua/practice7/entity input.xsd" xmlns:tns="http://sherbakov.nure.ua/practice7/entity">
    <Flower>
        <Name>Rose</Name>
        <Origin>Holland</Origin>
        <VisualParameters>
            <StalkColor/>
        </VisualParameters>
        <GrovingTips>
            <Temperature>20</Temperature>
            <Lighting>true</Lighting>
            <Watering>80</Watering>
        </GrovingTips>
        <Multipling>feces</Multipling>
        <Price>15.59</Price>
    </Flower>
    <Flower>
        <Name>Hedychium</Name>
        <Origin>South Asia</Origin>
        <VisualParameters>
            <StalkColor>Green</StalkColor>
        </VisualParameters>
        <GrovingTips>
            <Temperature>27</Temperature>
            <Lighting>false</Lighting>
            <Watering>105</Watering>
        </GrovingTips>
        <Multipling>FECES</Multipling>
        <Price>12.79</Price>
    </Flower>
    <Flower>
        <Name>Thoren</Name>
        <Origin>Asia</Origin>
        <VisualParameters>
            <StalkColor/>
        </VisualParameters>
        <GrovingTips>
            <Temperature>22</Temperature>
            <Lighting>true</Lighting>
            <Watering>60</Watering>
        </GrovingTips>
        <Multipling>SEEDS</Multipling>
        <Price>16.49</Price>
    </Flower>
    <Flower>
        <Name>Kermek</Name>
        <Origin>Asia</Origin>
        <VisualParameters>
            <StalkColor/>
        </VisualParameters>
        <GrovingTips>
            <Temperature>22</Temperature>
            <Lighting>true</Lighting>
            <Watering>60</Watering>
        </GrovingTips>
        <Multipling>SEEDS</Multipling>
        <Price>20.99</Price>
    </Flower>
    <Flower>
        <Name>Abelia</Name>
        <Origin>Japan</Origin>
        <VisualParameters>
            <StalkColor/>
        </VisualParameters>
        <GrovingTips>
            <Temperature>22</Temperature>
            <Lighting>true</Lighting>
            <Watering>60</Watering>
        </GrovingTips>
        <Multipling>SEEDS</Multipling>
        <Price>20.99</Price>
    </Flower>
</tns:Flowers>

=== legendarry24/Internet-Technologies/LAB34WebServer/input.xml
<?xml version="1.1" encoding="UTF-8"?>
<tns:Flowers
	xmlns:tns="http://sherbakov.nure.ua/practice7/entity"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://sherbakov.nure.ua/practice7/entity input.xsd ">

	<Flower id="1" Soil="podzolic">
		<Name>Rose</Name>
		<Origin>Holland</Origin>
		<VisualParameters>
			<StalkColor>Grey</StalkColor>
			<ColorOfLeaves>Red</ColorOfLeaves>
			<AveragePlantSize>60</AveragePlantSize>
		</VisualParameters>
		<GrovingTips>
			<Temperature>20</Temperature>
			<Watering>80</Watering>
			<Lighting>true</Lighting>
		</GrovingTips>
		<Multipling>feces</Multipling>
		<Price>15.59</Price>
	</Flower>

	<Flower id="2" Soil="wood-podzolic">
		<Name>Hedychium</Name>
		<Origin>South Asia</Origin>
		<VisualParameters>
			<StalkColor>Green</StalkColor>
			<ColorOfLeaves>Blue</ColorOfLeaves>
			<AveragePlantSize>12</AveragePlantSize>
		</VisualParameters>
		<GrovingTips>
			<Temperature>27</Temperature>
			<Watering>105</Watering>
			<Lighting>false</Lighting>
		</GrovingTips>
		<Multipling>feces</Multipling>
		<Price>12.79</Price>
	</Flower>

	<Flower id="3" Soil="unpaved">
		<Name>Thoren</Name>
		<Origin>Asia</Origin>
		<VisualParameters>
			<StalkColor>Green</StalkColor>
			<ColorOfLeaves>Violet</ColorOfLeaves>
			<AveragePlantSize>55</AveragePlantSize>
		</VisualParameters>
		<GrovingTips>
			<Watering>60</Watering>
			<Temperature>22</Temperature>
			<Lighting>true</Lighting>
		</GrovingTips>
		<Multipling>seeds</Multipling>
		<Price>16.49</Price>
	</Flower>

	<Flower id="4" Soil="unpaved">
		<Name>Kermek</Name>
		<Origin>Asia</Origin>
		<VisualParameters>
			<StalkColor>Green</StalkColor>
			<ColorOfLeaves>Blue</ColorOfLeaves>
			<AveragePlantSize>34</AveragePlantSize>
		</VisualParameters>
		<GrovingTips>
			<Watering>60</Watering>
			<Temperature>22</Temperature>
			<Lighting>true</Lighting>
		</GrovingTips>
		<Multipling>seeds</Multipling>
		<Price>20.99</Price>
	</Flower>

	<Flower id="5" Soil="unpaved">
		<Name>Abelia</Name>
		<Origin>Japan</Origin>
		<VisualParameters>
			<StalkColor>Green</StalkColor>
			<ColorOfLeaves>Violet</ColorOfLeaves>
			<AveragePlantSize>55</AveragePlantSize>
		</VisualParameters>
		<GrovingTips>
			<Watering>60</Watering>
			<Temperature>22</Temperature>
			<Lighting>true</Lighting>
		</GrovingTips>
		<Multipling>seeds</Multipling>
		<Price>17.59</Price>
	</Flower>
</tns:Flowers>
